# Generated by Django 6.0 on 2026-02-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='cinema',
        ),
        migrations.AddField(
            model_name='cinema',
            name='showtimes',
            field=models.ManyToManyField(blank=True, related_name='cinemas', to='cinemas.showtime'),
        ),
    ]
