# Generated by Django 6.0 on 2026-02-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('drama', 'درام'), ('comedy', 'کمدی'), ('action', 'اکشن'), ('romance', 'عاشقانه'), ('horror', 'ترسناک'), ('sci_fi', 'علمی تخیلی'), ('animation', 'انیمیشن'), ('thriller', 'هیجانی')], max_length=50),
        ),
    ]
